project_id = "opeadmwkryojfkxhnrix"

[functions.processing-callback]
verify_jwt = false

[functions.polar-webhook]
verify_jwt = false

[functions.credits-webhook]
verify_jwt = false

[functions.remove-watermark]
verify_jwt = true

[functions.purchase-credits]
verify_jwt = true